name: bceao_pi
description: Module BCEAO Payments
version: 0.0.1

environment:
  sdk: '>=3.10.0 <5.0.0'

dependencies:
  flutter:
    sdk: flutter
  micro_core:
    path: ../../micro_core
  micro_commons:
    path: ../../micro_commons

dev_dependencies:
  flutter_test:
    sdk: flutter
